CREATE TABLE [dbo].[DispatchDataTable]
(
	[projectdatettime] DATETIME NOT NULL, 
    [projectno] NVARCHAR(50) NOT NULL, 
    [ownername] NVARCHAR(50) NOT NULL, 
    [owneraddress] NVARCHAR(MAX) NOT NULL, 
    [ownerno] NVARCHAR(50) NOT NULL, 
    [workstartdate] DATETIME NOT NULL, 
    [workenddate] DATETIME NOT NULL, 
    [contact] NVARCHAR(50) NOT NULL, 
    [contactphone] NVARCHAR(50) NOT NULL, 
    [projectleader] NVARCHAR(50) NOT NULL, 
    [projectworkleader] NVARCHAR(50) NOT NULL, 
    [bargainperson] NVARCHAR(50) NOT NULL, 
    [bargainyesornot] BIT NOT NULL, 
    [bargainrenson] NVARCHAR(MAX) NOT NULL, 
    [bargaindate] DATETIME NOT NULL, 
    [bargainlocal] NVARCHAR(MAX) NOT NULL, 
    [bargainprice] NVARCHAR(50) NOT NULL, 
    [bargainmoney] INT NOT NULL, 
    [quotationcode] NVARCHAR(50) NOT NULL, 
    [quotationprice] INT NOT NULL, 
    [insuranceyesornot] BIT NOT NULL, 
    [insurancestartdate] DATETIME NOT NULL, 
    [insuranceenddate] DATETIME NOT NULL, 
    [contractmoney] INT NOT NULL, 
    [contractmoneyyesornot] BIT NOT NULL, 
    [plancost] NVARCHAR(50) NOT NULL, 
    [contractcost] BIT NOT NULL, 
    [plangoal] NVARCHAR(50) NOT NULL, 
    [ponumber] NVARCHAR(50) NOT NULL, 
    CONSTRAINT [PK_DispatchDataTable] PRIMARY KEY ([projectno]) 
)
