CREATE TABLE [dbo].[PurchasePlan] (
    [pk]                    INT           NOT NULL,
    [ProjectNO]             NVARCHAR (50) NOT NULL,
    [Code]             NVARCHAR (50) NOT NULL,
    [ProjectItem]           INT           NOT NULL,
    [ProjectCode]           NVARCHAR (50) NOT NULL,
    [ProjectPurchaser]      NVARCHAR (50) NOT NULL,
    [ProjectContent]        NVARCHAR (50) NOT NULL,
    [EstimatedMailDate]     DATETIME      NULL,
    [RealMailDate]          DATETIME      NULL,
    [BuyMan]                NVARCHAR (50) NOT NULL,
    [EstimatedDecisionDate] DATETIME      NULL,
    [RaelDecisionDate]      DATETIME      NULL,
    [LongTimeDevice]        BIT           NULL,
    [ContactCode]           NVARCHAR (50) NULL,
    [ErrorCode]             NVARCHAR (50) NULL,
    [Vendor]                NVARCHAR (50) NULL,
    [OrderCode]             NVARCHAR (50) NULL,
    [ContactPerson]         NVARCHAR (50) NULL,
    [ContactPersonPhone]    NVARCHAR (50) NULL,
    [EstimatedCost]         INT           NOT NULL,
    [ExecutionGoal]         INT           NOT NULL,
    [PackageCoin]           INT           NULL,
    [NuPackageCoin]         INT           NOT NULL,
    [Subtotal]              INT           NOT NULL,
    [DiffCoin]              INT           NOT NULL,
    [AccCoin]               INT           NULL,
    [Remark]                NVARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([pk] ASC)
);

